spring.application.name=wotandme

jwt.secret=mZ7Jx7sJX3kF4Zp5n8W2cL1tQ9vR6yT0aBcDeFgHiJk=
jwt.expiration=86400000

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false

app.id=bfe4352027495c7b1c12472986bd88b3
api.account.list=?application_id=